#!/usr/bin/env bash

./querybook/scripts/init_db

flask_server() {
    # Restart flask server in case of crash; since we are running webpack at the same time
    # Docker would not restart web container in case of syntax error
    while true; do
        ./querybook/scripts/runservice web --debug ${APIPORT-3000} && break
        sleep 5
    done
}
webpack_server() {
    yarn run webpack-dev-server \
        --host 0.0.0.0 \
        --port ${PORT-10001} \
        --mode=development --open --hot \
        --env.QUERYBOOK_UPSTREAM=http://0.0.0.0:${APIPORT-3000}
}

if [ "$HOT_RELOAD" = "true" ]; then
    { flask_server & webpack_server; }
else
    ./querybook/scripts/runservice web --debug --webpack ${PORT-10001}
fi
