version: '2.1'

services:
    docs:
        build:
            context: .
            dockerfile: ./docs_website/Dockerfile
        container_name: querybook_docs
        network_mode: 'host'
        environment:
            PORT: ${PORT:-3000}
