repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.4.0
      hooks:
          - id: trailing-whitespace
            exclude: ^datahub/webapp/__tests__/ui/__snapshots__/
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/psf/black
      rev: 19.10b0
      hooks:
          - id: black
            files: "^datahub/(server|tests)/.*\\.py$"
    - repo: https://github.com/prettier/prettier
      rev: '2.0.2'
      hooks:
          - id: prettier
            files: "^datahub/webapp/.*\\.(tsx?)$"
    - repo: https://gitlab.com/pycqa/flake8
      rev: '3.7.9'
      hooks:
          - id: flake8
            files: "^datahub/(server|tests)/.*\\.py$"
            exclude: ^datahub/migrations/.*
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: '6.8.0' # Use the sha / tag you want to point at
    #   files: 'datahub/webapp/.*\\.(tsx?)$'
    #   hooks:
    #       - id: eslint
