repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.2.0
      hooks:
          - id: trailing-whitespace
            exclude: ^querybook/webapp/__tests__/ui/__snapshots__/
          - id: end-of-file-fixer
          - id: check-yaml
            exclude: ^helm/templates/
          - id: check-added-large-files
            args: ['--maxkb=10000']
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
          - id: black
            files: "^querybook/(server|tests)/.*\\.py$"
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.6.2'
      hooks:
          - id: prettier
            files: "^querybook/webapp/.*\\.(tsx?)$"
            additional_dependencies:
                - prettier@2.2.1
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            files: "^querybook/(server|tests)/.*\\.py$"
            exclude: ^querybook/migrations/.*
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: '6.8.0' # Use the sha / tag you want to point at
    #   files: 'querybook/webapp/.*\\.(tsx?)$'
    #   hooks:
    #       - id: eslint
