{
    "name": "querybook",
    "version": "3.32.0",
    "description": "A Big Data Webapp",
    "private": true,
    "scripts": {
        "test": "jest",
        "build": "npx webpack",
        "storybook": "STORYBOOK_USER=${USER} start-storybook -s ./querybook/static:/static -p 6006",
        "build-storybook": "build-storybook",
        "dev": "webpack serve --mode=development --open --hot",
        "lint": "eslint 'querybook/webapp/*/**/*.{ts,tsx}' --quiet --fix",
        "tsc-check": "tsc --noEmit"
    },
    "repository": {
        "type": "git",
        "url": "git+ssh://git@github.com:pinterest/querybook.git"
    },
    "keywords": [
        "querybook",
        "big",
        "data",
        "hive",
        "presto"
    ],
    "author": "Analytics Platform",
    "bugs": {
        "url": "https://github.com/pinterest/querybook/issues"
    },
    "homepage": "https://github.com/pinterest/querybook",
    "engines": {
        "node": ">=14.0.0"
    },
    "dependencies": {
        "@babel/core": "^7.16.0",
        "@babel/preset-env": "^7.16.0",
        "@babel/preset-react": "^7.16.0",
        "@babel/preset-typescript": "^7.16.0",
        "@types/diff": "^5.0.2",
        "@welldone-software/why-did-you-render": "^6.1.1",
        "axios": "^1.2.2",
        "bignumber.js": "^9.0.1",
        "chart.js": "^3.9.1",
        "chartjs-adapter-moment": "^1.0.0",
        "chartjs-plugin-datalabels": "^2.1.0",
        "clean-webpack-plugin": "3.0.0",
        "clsx": "^1.2.1",
        "codemirror": "^5.64.0",
        "core-decorators": "0.20.0",
        "core-js": "^3.19.1",
        "cron-parser": "^4.7.0",
        "dagre": "^0.8.5",
        "dompurify": "^3.0.9",
        "draft-js": "0.11.7",
        "draft-js-export-html": "^1.4.1",
        "draft-js-import-html": "^1.4.1",
        "fast-json-stable-stringify": "^2.1.0",
        "formik": "^2.2.9",
        "history": "^4.10.1",
        "html-webpack-plugin": "5.3.1",
        "immer": "^9.0.17",
        "immutable": "3.7.4",
        "jsdiff": "^1.1.1",
        "json-bigint": "^1.0.0",
        "localforage": "^1.10.0",
        "lodash": "4.17.21",
        "lodash-decorators": "6.0.1",
        "lucide-react": "^0.187.0",
        "markdown-to-jsx": "^7.1.0",
        "memoize-one": "^6.0.0",
        "mini-css-extract-plugin": "^2.7.2",
        "moment": "2.29.4",
        "normalizr": "^3.6.2",
        "qs": "^6.11.0",
        "rc-time-picker": "3.6.4",
        "re-resizable": "4.9.0",
        "react": "17.0.2",
        "react-chartjs-2": "3.0.4",
        "react-codemirror2": "7.2.1",
        "react-dnd": "^15.1.2",
        "react-dnd-html5-backend": "^15.1.2",
        "react-dom": "17.0.2",
        "react-hot-toast": "^2.4.0",
        "react-json-view": "^1.21.3",
        "react-lazyload": "^3.2.0",
        "react-redux": "7.2.4",
        "react-router-dom": "5.1.2",
        "react-select": "4.3.1",
        "react-table": "6.8.6",
        "react-virtualized": "9.22.3",
        "reactflow": "^11.3.0",
        "reactour": "^1.18.6",
        "redux": "4.1.0",
        "redux-logger": "3.0.6",
        "redux-thunk": "2.3.0",
        "regenerator-runtime": "^0.13.7",
        "reselect": "4.0.0",
        "sass": "^1.50.0",
        "smooth-scroll-into-view-if-needed": "^1.1.27",
        "socket.io-client": "^4.5.2",
        "sql-formatter": "^12.1.2",
        "styled-components": "5.3.9",
        "typescript": "4.4.4",
        "webpack": "5.76.0",
        "webpack-cli": "4.7.0",
        "yaml-loader": "^0.8.0",
        "yup": "^0.32.11"
    },
    "devDependencies": {
        "@babel/plugin-proposal-class-properties": "^7.12.1",
        "@babel/plugin-proposal-decorators": "^7.12.12",
        "@babel/plugin-proposal-nullish-coalescing-operator": "^7.12.1",
        "@babel/plugin-proposal-optional-chaining": "^7.12.7",
        "@pmmmwh/react-refresh-webpack-plugin": "0.5.0-rc.2",
        "@storybook/addon-centered": "^5.3.21",
        "@storybook/addon-essentials": "^6.5.12",
        "@storybook/addon-links": "^6.5.12",
        "@storybook/addons": "^6.5.12",
        "@storybook/builder-webpack5": "^6.5.12",
        "@storybook/manager-webpack5": "^6.5.12",
        "@storybook/react": "^6.5.12",
        "@trivago/prettier-plugin-sort-imports": "^3.2.0",
        "@types/codemirror": "^5.60.5",
        "@types/d3": "^5.7.2",
        "@types/dagre-d3": "0.4.38",
        "@types/draft-js": "0.10.44",
        "@types/fast-json-stable-stringify": "2.0.0",
        "@types/jest": "^26.0.20",
        "@types/json-bigint": "^1.0.0",
        "@types/lodash": "4.14.116",
        "@types/markdown-to-jsx": "^6.11.3",
        "@types/memoize-one": "3.1.1",
        "@types/qs": "^6.9.7",
        "@types/rc-time-picker": "^3.4.1",
        "@types/react": "17.0.15",
        "@types/react-dom": "17.0.9",
        "@types/react-lazyload": "2.6.0",
        "@types/react-redux": "7.1.18",
        "@types/react-router-dom": "5.1.3",
        "@types/react-select": "4.0.17",
        "@types/react-table": "6.7.13",
        "@types/react-virtualized": "9.21.12",
        "@types/reactour": "^1.18.2",
        "@types/redux-logger": "3.0.6",
        "@types/resize-observer-browser": "^0.1.4",
        "@types/sql-formatter": "^2.3.0",
        "@types/styled-components": "5.1.4",
        "@types/webpack": "5.28.0",
        "@types/webpack-env": "1.16.0",
        "@types/yup": "^0.29.13",
        "@typescript-eslint/eslint-plugin": "^5.28.0",
        "@typescript-eslint/eslint-plugin-tslint": "^5.28.0",
        "@typescript-eslint/parser": "^5.28.0",
        "@wojtekmaj/enzyme-adapter-react-17": "^0.6.3",
        "babel-jest": "^26.6.3",
        "babel-loader": "^8.2.2",
        "babel-plugin-styled-components": "^1.12.0",
        "babel-plugin-transform-imports": "^2.0.0",
        "css-loader": "5.2.4",
        "csstype": "2.5.7",
        "enzyme": "^3.11.0",
        "enzyme-to-json": "^3.4.3",
        "eslint": "^8.17.0",
        "eslint-config-prettier": "^8.5.0",
        "eslint-plugin-jsdoc": "^39.3.2",
        "eslint-plugin-prefer-arrow": "^1.2.3",
        "eslint-plugin-react": "^7.30.0",
        "eslint-plugin-react-hooks": "^4.6.0",
        "eslint-plugin-unused-imports": "^2.0.0",
        "jest": "26.6.3",
        "jest-esm-transformer": "^1.0.0",
        "js-yaml": "^4.1.0",
        "postcss-loader": "^6.1.0",
        "postcss-preset-env": "6.7.0",
        "prettier": "2.7.1",
        "prettier-eslint": "^15.0.1",
        "react-refresh": "^0.10.0",
        "sass-loader": "11.1.0",
        "source-map-loader": "2.0.1",
        "style-loader": "2.0.0",
        "tslint": "^6.1.3",
        "webpack-dev-server": "^3.11.2"
    }
}
