apiVersion: v1
kind: Secret
metadata:
  name: {{ include "querybook.fullname" . }}-secret
  labels:
    app: {{ include "querybook.name" . }}
    chart: {{ include "querybook.chart" . }}
    component: secret
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  FLASK_SECRET_KEY: {{ .Values.secret.flask_secret_key | toString | b64enc }}
  DATABASE_CONN: {{ .Values.secret.database_conn | toString | b64enc }}
  REDIS_URL: {{ .Values.secret.redis_url | toString | b64enc }}
  ELASTICSEARCH_HOST: {{ .Values.secret.elasticsearch_host | toString | b64enc }}
