"""Update DataTableOwnership

Revision ID: 2dc98d5f4c43
Revises: dc68ab1e12b9
Create Date: 2020-08-26 21:42:28.194672

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2dc98d5f4c43'
down_revision = 'dc68ab1e12b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_ownership', sa.Column(
        'uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_table_ownership', 'user', ['uid'], ['id'])
    op.drop_column('data_table_ownership', 'owner')
    op.create_unique_constraint(
        'unique_table_ownership',
        'data_table_ownership',
        ['data_table_id', 'uid']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_ownership', sa.Column(
        'owner', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'data_table_ownership', type_='foreignkey')
    op.drop_column('data_table_ownership', 'uid')
    # ### end Alembic commands ###
