"""Add unique constraint to DataTableOwner

Revision ID: 3682293f48f2
Revises: dc68ab1e12b9
Create Date: 2020-08-26 20:43:24.258971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3682293f48f2'
down_revision = 'dc68ab1e12b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        'unique_table_ownership',
        'data_table_ownership',
        ['data_table_id', 'owner']
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_table_ownership', 'data_table_ownership')
    # ### end Alembic commands ###
