"""Add Tag and TagItem

Revision ID: 4bfbcee641dc
Revises: 8e3a8aa02aa7
Create Date: 2020-08-27 23:19:33.545740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bfbcee641dc'
down_revision = '8e3a8aa02aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('count', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    op.create_table('tag_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('tag_name', sa.String(length=255), nullable=False),
                    sa.Column('table_id', sa.Integer(), nullable=True),
                    sa.Column('uid', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['table_id'], ['data_table.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['tag_name'], ['tag.name'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='NO ACTION'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_item')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
