"""Update DataTableOwnership

Revision ID: 8e3a8aa02aa7
Revises: dc68ab1e12b9
Create Date: 2020-08-26 23:01:04.912894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e3a8aa02aa7'
down_revision = 'dc68ab1e12b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_table_ownership', 'data_table_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.create_foreign_key(None, 'data_table_ownership', 'data_table',
                          ['data_table_id'], ['id'], ondelete='CASCADE')

    op.add_column('data_table_ownership', sa.Column(
        'uid', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'data_table_ownership', 'user',
                          ['uid'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(
        'unique_table_ownership',
        'data_table_ownership',
        ['data_table_id', 'uid'])

    op.drop_column('data_table_ownership', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_ownership', sa.Column(
        'owner', mysql.VARCHAR(length=255), nullable=True))

    op.drop_constraint('unique_table_ownership', 'data_table_ownership', type_='unique')

    op.drop_column('data_table_ownership', 'uid')

    op.drop_constraint(None, 'data_table_ownership', type_='foreignkey')
    op.alter_column('data_table_ownership', 'data_table_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    # ### end Alembic commands ###
