"""Add Query Execution Viewer table


Revision ID: c15cc6c6bee7
Revises: 178d6726310a
Create Date: 2020-08-25 15:40:46.215244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15cc6c6bee7'
down_revision = '178d6726310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_execution_viewer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_execution_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['query_execution_id'], ['query_execution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_execution_id', 'uid', name='unique_query_execution_viewer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_execution_viewer')
    # ### end Alembic commands ###
