"""Add Query Execution Viewer Table

Revision ID: f93d62f9a53d
Revises: 178d6726310a
Create Date: 2020-08-27 17:47:02.179572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f93d62f9a53d'
down_revision = '178d6726310a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_execution_viewer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_execution_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['query_execution_id'], ['query_execution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query_execution_id', 'uid', name='unique_query_execution_viewer')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_execution_viewer')
    # ### end Alembic commands ###
