"""Add access request table

Revision ID: fb7550640189
Revises: 1f1bf1af5704
Create Date: 2020-08-07 08:17:34.318853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7550640189'
down_revision = '1f1bf1af5704'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_request',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('data_doc_id', sa.Integer(), nullable=True),
    sa.Column('query_execution_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_doc_id'], ['data_doc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['query_execution_id'], ['query_execution.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_doc_id', 'uid', name='unique_data_doc_access_request'),
    sa.UniqueConstraint('query_execution_id', 'uid', name='unique_query_execution_access_request')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('access_request')
    # ### end Alembic commands ###
