"""tracking url to meta info

Revision ID: 0463ffd9a113
Revises: eb59b7321afc
Create Date: 2019-10-03 00:23:41.896440

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "0463ffd9a113"
down_revision = "eb59b7321afc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "statement_execution",
        "tracking_url",
        new_column_name="meta_info",
        nullable=True,
        existing_type=sa.String(length=2083),
        type_=sa.String(length=5000),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "statement_execution",
        "meta_info",
        new_column_name="tracking_url",
        nullable=True,
        existing_type=sa.String(length=5000),
        type_=sa.String(length=2083),
    )
    # ### end Alembic commands ###
