"""update metastore

Revision ID: 174e15ef7026
Revises: 5d2bcec52640
Create Date: 2019-09-12 23:47:41.311626

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "174e15ef7026"
down_revision = "5d2bcec52640"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_metastore",
        "metastore_url",
        new_column_name="metastore_params",
        nullable=True,
        existing_type=sa.JSON(),
    )
    op.add_column(
        "query_metastore", sa.Column("loader", sa.String(length=128), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_metastore",
        "metastore_params",
        new_column_name="metastore_url",
        nullable=True,
        existing_type=sa.JSON(),
    )
    op.drop_column("query_metastore", "loader")
    # ### end Alembic commands ###
