"""add dag exporter

Revision ID: 17f7c039ab6e
Revises: d4ff446a8436
Create Date: 2022-04-25 21:38:01.176777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "17f7c039ab6e"
down_revision = "d4ff446a8436"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_doc_dag_export",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data_doc_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("dag", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["data_doc_id"],
            ["data_doc.id"],
            name="dag_export_data_doc_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("data_doc_id", name="unique_dag_export_data_doc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_doc_dag_export")
    # ### end Alembic commands ###
