"""update board and board item descriptions

Revision ID: 1e3eb54fcb83
Revises: b8a9e3e18bcc
Create Date: 2021-03-23 21:00:35.909596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e3eb54fcb83'
down_revision = 'b8a9e3e18bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('board_item', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_cell', 'context',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_job_metadata', 'query_text',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_schema', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_table_column', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_table_information', 'description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('data_table_information', 'hive_metastore_description',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('key_value_store', 'value',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('query_execution', 'query',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    op.alter_column('query_execution_error', 'error_message',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.Text(length=65535),
               existing_nullable=True)
    op.alter_column('query_metastore', 'acl_control',
               existing_type=mysql.MEDIUMTEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('query_snippet', 'context',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_snippet', 'context',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('query_metastore', 'acl_control',
               existing_type=sa.JSON(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('query_execution_error', 'error_message',
               existing_type=sa.Text(length=65535),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('query_execution', 'query',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('key_value_store', 'value',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('data_table_information', 'hive_metastore_description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('data_table_information', 'description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('data_table_column', 'description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('data_schema', 'description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('data_job_metadata', 'query_text',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('data_cell', 'context',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=True)
    op.alter_column('board_item', 'description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('board', 'description',
               existing_type=sa.Text(length=16777215),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
