"""update board and board item descriptions

Revision ID: 1e3eb54fcb83
Revises: b8a9e3e18bcc
Create Date: 2021-03-23 21:00:35.909596

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e3eb54fcb83'
down_revision = 'b8a9e3e18bcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board_item',
                  sa.Column('description', sa.Text(length=16777215), nullable=True))
    op.alter_column('board', 'description',
                    existing_type=sa.String(length=5000),
                    type_=sa.Text(length=16777215),
                    existing_nullable=True)
    op.alter_column('query_metastore', 'acl_control',
                    existing_type=sa.Text(length=16777215),
                    type_=sa.JSON(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('query_metastore', 'acl_control',
                    existing_type=sa.JSON(),
                    type_=sa.Text(length=16777215),
                    existing_nullable=False)
    op.alter_column('board', 'description',
                    existing_type=sa.Text(length=16777215),
                    type_=sa.String(length=5000),
                    existing_nullable=True)
    op.drop_column('board_item', 'description')
    # ### end Alembic commands ###
