"""add execute permission level for datadocs

Revision ID: 1e477e1b711a
Revises: e7a17a8acf4c
Create Date: 2025-10-02 00:32:17.602058

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e477e1b711a'
down_revision = 'e7a17a8acf4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_doc_editor', sa.Column('execute', sa.Boolean(), nullable=False, server_default='0'))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_doc_editor', 'execute')
    # ### end Alembic commands ###
