"""add table boost score

Revision ID: 1f1bf1af5704
Revises: 6ae7878fdcf6
Create Date: 2020-07-15 23:07:55.563358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f1bf1af5704"
down_revision = "6ae7878fdcf6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_table",
        sa.Column(
            "boost_score", sa.Float(), nullable=False, server_default=sa.text("1"),
        ),
    )
    op.execute("UPDATE data_table SET boost_score = 1")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_table", "boost_score")
    # ### end Alembic commands ###
