"""Add event logs

Revision ID: 2dc4b2f93081
Revises: 7f368cb1c51b
Create Date: 2022-11-07 20:10:31.068043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2dc4b2f93081'
down_revision = '7f368cb1c51b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('API', 'VIEW', 'CLICK', name='eventtype'), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_log_event_type'), 'event_log', ['event_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_log_event_type'), table_name='event_log')
    op.drop_table('event_log')
    # ### end Alembic commands ###
