"""add query as board item

Revision ID: 30f762fd1fa4
Revises: f449a73c5838
Create Date: 2022-06-28 20:17:26.668477

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "30f762fd1fa4"
down_revision = "f449a73c5838"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "board_item", sa.Column("query_execution_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "board_item_query_id_fk",
        "board_item",
        "query_execution",
        ["query_execution_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("board_item_query_id_fk", "board_item", type_="foreignkey")
    op.create_foreign_key(
        "board_item_ibfk_1",
        "board_item",
        "board",
        ["parent_board_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
