"""Add generic user info field

Revision ID: 598d02b40642
Revises: ee6d402f1d88
Create Date: 2020-03-20 18:18:50.516311

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "598d02b40642"
down_revision = "ee6d402f1d88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("properties", sa.JSON(), nullable=True))

    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.execute("""UPDATE "user" SET properties='{}'""")
    elif conn.dialect.name == "mysql":
        op.execute("UPDATE `user` SET properties = '{}'")
    else:
        op.execute("UPDATE user SET properties = '{}'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "properties")
    # ### end Alembic commands ###
