"""add scheduled for datadoc

Revision ID: 5b94e0164a3b
Revises: f449a73c5838
Create Date: 2022-08-24 15:43:58.148958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5b94e0164a3b'
down_revision = 'f449a73c5838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_doc', sa.Column('scheduled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_doc', 'scheduled')
    # ### end Alembic commands ###
