"""Add deleted_at field

Revision ID: 5d2bcec52640
Revises: 22c9a254b41e
Create Date: 2019-07-19 22:45:23.485884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d2bcec52640'
down_revision = '22c9a254b41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_engine', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('query_metastore', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_metastore', 'deleted_at')
    op.drop_column('query_engine', 'deleted_at')
    # ### end Alembic commands ###
