"""add hidden to environment and task type to task schedule

Revision ID: 5dc5d5993051
Revises: 8fe263c58150
Create Date: 2020-02-03 19:32:51.533316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5dc5d5993051"
down_revision = "8fe263c58150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("environment", sa.Column("hidden", sa.Boolean(), nullable=True))
    op.create_foreign_key(
        "task_run_record_task_schedule_fk",
        "task_run_record",
        "task_schedule",
        ["name"],
        ["name"],
        ondelete="CASCADE",
    )
    op.add_column(
        "task_schedule",
        sa.Column(
            "task_type",
            sa.String(length=255),
            nullable=False,
            server_default=sa.text("'prod'"),
        ),
    )
    op.execute("UPDATE task_schedule SET task_type = 'user' WHERE name like 'run%'")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task_schedule", "task_type")
    op.drop_constraint(
        "task_run_record_task_schedule_fk", "task_run_record", type_="foreignkey"
    )
    op.drop_column("environment", "hidden")
    # ### end Alembic commands ###
