"""Add created for userenv, add errormsg for task

Revision ID: 6ae7878fdcf6
Revises: 3a40f1143ab4
Create Date: 2020-06-23 23:47:52.985072

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6ae7878fdcf6"
down_revision = "3a40f1143ab4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task_run_record",
        sa.Column("error_message", sa.String(length=5000), nullable=True),
    )
    op.drop_column("task_run_record", "alerted")
    op.add_column(
        "user_environment", sa.Column("created_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_environment", "created_at")
    op.add_column(
        "task_run_record",
        sa.Column("alerted", sa.Boolean(), autoincrement=False, nullable=True,),
    )
    op.drop_column("task_run_record", "error_message")
    # ### end Alembic commands ###
