"""consolidate to deleted_at

Revision ID: 6dc1b92d6b50
Revises: 5dc5d5993051
Create Date: 2020-02-04 22:03:53.699107

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6dc1b92d6b50"
down_revision = "5dc5d5993051"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("environment", sa.Column("deleted_at", sa.DateTime(), nullable=True))
    op.drop_column("environment", "archived")
    op.drop_column("query_engine", "archived")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "query_engine",
        sa.Column("archived", sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "environment",
        sa.Column("archived", sa.Boolean(), autoincrement=False, nullable=True),
    )
    op.drop_column("environment", "deleted_at")
    # ### end Alembic commands ###
