"""Add shareable env

Revision ID: 7622e103dabf
Revises: 598d02b40642
Create Date: 2020-03-30 15:49:56.317402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7622e103dabf"
down_revision = "598d02b40642"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "environment",
        sa.Column(
            "shareable", sa.Boolean(), nullable=True, server_default=sa.text("true")
        ),
    )
    op.execute("UPDATE environment SET shareable = true")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("environment", "shareable")
    # ### end Alembic commands ###
