"""add table links to datatable

Revision ID: 767cf0f573bd
Revises: 299e24dcfd29
Create Date: 2024-05-09 18:17:17.799678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '767cf0f573bd'
down_revision = '299e24dcfd29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_information', sa.Column('table_links', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_table_information', 'table_links')
    # ### end Alembic commands ###
