"""add table ownership type

Revision ID: 78980ea69b46
Revises: cf334666f8f6
Create Date: 2023-02-16 23:07:20.242691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78980ea69b46'
down_revision = 'cf334666f8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_ownership', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_table_ownership', 'type')
    # ### end Alembic commands ###
