"""Add admin audit logs

Revision ID: 7a7b02af3f1b
Revises: 7622e103dabf
Create Date: 2020-04-10 16:27:14.265008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7a7b02af3f1b"
down_revision = "7622e103dabf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("uid", sa.Integer(), nullable=True),
        sa.Column("item_type", sa.String(length=255), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column(
            "op",
            sa.Enum("CREATE", "UPDATE", "DELETE", name="adminoperation"),
            nullable=False,
        ),
        sa.Column("log", sa.String(length=5000), nullable=True),
        sa.ForeignKeyConstraint(
            ["uid"], ["user.id"], name="admin_audit_log_ibfk_1", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("admin_audit_log")
    # ### end Alembic commands ###
    conn = op.get_bind()
    if conn.dialect.name == "postgresql":
        op.execute("DROP TYPE adminoperation")
