"""Allow DataTable/ColumnStats uid to be Null

Revision ID: 7d24ddb3edb9
Revises: 3ff3ad7e4669
Create Date: 2020-09-11 18:19:38.839580

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7d24ddb3edb9"
down_revision = "3ff3ad7e4669"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "data_table_column_statistics",
        "uid",
        existing_type=sa.Integer(),
        nullable=True,
    )
    op.alter_column(
        "data_table_statistics", "uid", existing_type=sa.Integer(), nullable=True,
    )
    op.drop_constraint("fk_tag_item_user", "tag_item", type_="foreignkey")
    op.create_foreign_key(
        "tag_item_ibfk_1", "tag_item", "user", ["uid"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tag_item_ibfk_1", "tag_item", type_="foreignkey")
    op.create_foreign_key("fk_tag_item_user", "tag_item", "user", ["uid"], ["id"])
    op.alter_column(
        "data_table_statistics", "uid", existing_type=sa.Integer(), nullable=False,
    )
    op.alter_column(
        "data_table_column_statistics",
        "uid",
        existing_type=sa.Integer(),
        nullable=False,
    )
    # ### end Alembic commands ###
