"""data_doc_tag_item

Revision ID: 8f194c1b59a3
Revises: 7f6cdb3621f7
Create Date: 2023-06-01 20:40:07.871141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f194c1b59a3'
down_revision = '7f6cdb3621f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_doc_tag_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tag_name', sa.String(length=255), nullable=False),
    sa.Column('datadoc_id', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['datadoc_id'], ['data_doc.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uid'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_doc_tag_item')
    # ### end Alembic commands ###
