"""boards

Revision ID: 8fe263c58150
Revises: 0463ffd9a113
Create Date: 2019-12-23 22:13:42.073755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8fe263c58150"
down_revision = "0463ffd9a113"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=5000), nullable=True),
        sa.Column("public", sa.Boolean(), nullable=True),
        sa.Column("board_type", sa.String(length=255), nullable=True),
        sa.Column("environment_id", sa.Integer(), nullable=False),
        sa.Column("owner_uid", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["environment_id"],
            ["environment.id"],
            name="board_ibfk_1",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_uid"], ["user.id"], name="board_ibfk_2", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "board_item",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("data_doc_id", sa.Integer(), nullable=True),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("item_order", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["board_id"], ["board.id"], name="board_item_ibfk_1", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["data_doc_id"],
            ["data_doc.id"],
            name="board_item_ibfk_2",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["data_table.id"],
            name="board_item_ibfk_3",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("board_item")
    op.drop_table("board")
    # ### end Alembic commands ###
