"""add table custom properties

Revision ID: adfbd684e30c
Revises: 1b8aba201c94
Create Date: 2023-02-14 22:38:27.419052

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'adfbd684e30c'
down_revision = '1b8aba201c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_information', sa.Column('custom_properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_table_information', 'custom_properties')
    # ### end Alembic commands ###
