"""add more cascade relationship

Revision ID: b8a9e3e18bcc
Revises: 7d24ddb3edb9
Create Date: 2020-12-15 19:54:55.906997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8a9e3e18bcc"
down_revision = "7d24ddb3edb9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("data_doc_editor_ibfk_1", "data_doc_editor", type_="foreignkey")
    op.create_foreign_key(
        "data_doc_editor_ibfk_3",
        "data_doc_editor",
        "data_doc",
        ["data_doc_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "job_metadata_metastore_fk", "data_job_metadata", type_="foreignkey"
    )
    op.create_foreign_key(
        "job_metadata_metastore_fk",
        "data_job_metadata",
        "query_metastore",
        ["metastore_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("data_schema_ibfk_1", "data_schema", type_="foreignkey")
    op.create_foreign_key(
        "data_schema_ibfk_1",
        "data_schema",
        "query_metastore",
        ["metastore_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("data_schema_ibfk_1", "data_schema", type_="foreignkey")
    op.create_foreign_key(
        "data_schema_ibfk_1", "data_schema", "query_metastore", ["metastore_id"], ["id"]
    )
    op.drop_constraint(
        "job_metadata_metastore_fk", "data_job_metadata", type_="foreignkey"
    )
    op.create_foreign_key(
        "job_metadata_metastore_fk",
        "data_job_metadata",
        "query_metastore",
        ["metastore_id"],
        ["id"],
    )
    op.drop_constraint("data_doc_editor_ibfk_3", "data_doc_editor", type_="foreignkey")
    op.create_foreign_key(
        "data_doc_editor_ibfk_1", "data_doc_editor", "data_doc", ["data_doc_id"], ["id"]
    )
    # ### end Alembic commands ###
