"""add column tags support

Revision ID: cf334666f8f6
Revises: adfbd684e30c
Create Date: 2023-02-16 00:25:05.116326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cf334666f8f6'
down_revision = 'adfbd684e30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_item', sa.Column('column_id', sa.Integer(), nullable=True))
    op.create_foreign_key("fk_tag_item_data_table_column", 'tag_item', 'data_table_column', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_tag_item_data_table_column", 'tag_item', type_='foreignkey')
    op.drop_column('tag_item', 'column_id')
    # ### end Alembic commands ###
