"""add tag meta

Revision ID: d4ff446a8436
Revises: 8e6d5acc7be1
Create Date: 2022-05-17 18:37:31.927851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "d4ff446a8436"
down_revision = "8e6d5acc7be1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tag", sa.Column("meta", sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tag", "meta")
    # ### end Alembic commands ###
