"""data_job_metadata and table_lineage update

Revision ID: eb59b7321afc
Revises: 174e15ef7026
Create Date: 2019-09-25 19:42:56.707064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb59b7321afc"
down_revision = "174e15ef7026"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_job_metadata", sa.Column("metastore_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "job_metadata_metastore_fk",
        "data_job_metadata",
        "query_metastore",
        ["metastore_id"],
        ["id"],
    )
    op.create_unique_constraint(
        "unique_table_lineage",
        "table_lineage",
        ["table_id", "parent_table_id", "job_metadata_id"],
    )
    op.drop_constraint("table_lineage_ibfk_1", "table_lineage", type_="foreignkey")
    op.create_foreign_key(
        "table_lineage_table_fk",
        "table_lineage",
        "data_table",
        ["table_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "table_lineage_job_metadata_fk",
        "table_lineage",
        "data_job_metadata",
        ["job_metadata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "table_lineage_job_metadata_fk", "table_lineage", type_="foreignkey"
    )
    op.drop_constraint("table_lineage_table_fk", "table_lineage", type_="foreignkey")

    if conn.dialect.name == "mysql":
        op.drop_constraint("table_lineage_ibfk_2", "table_lineage", type_="foreignkey")
        op.drop_constraint("table_lineage_ibfk_3", "table_lineage", type_="foreignkey")

    op.drop_constraint("unique_table_lineage", "table_lineage", type_="unique")
    if conn.dialect.name == "mysql":
        op.create_foreign_key(
            "table_lineage_ibfk_2",
            "table_lineage",
            "data_table",
            ["parent_table_id"],
            ["id"],
            ondelete="CASCADE",
        )
        op.create_foreign_key(
            "table_lineage_ibfk_3", "table_lineage", "data_table", ["table_id"], ["id"],
        )

    op.create_foreign_key(
        "table_lineage_ibfk_1",
        "table_lineage",
        "data_job_metadata",
        ["job_metadata_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        "job_metadata_metastore_fk", "data_job_metadata", type_="foreignkey"
    )
    op.drop_column("data_job_metadata", "metastore_id")

    # ### end Alembic commands ###
