"""add more metadata support

Revision ID: ec2f32c25f34
Revises: 1b8aba201c94
Create Date: 2023-02-24 23:46:29.304134

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'ec2f32c25f34'
down_revision = '1b8aba201c94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_table_information', sa.Column('custom_properties', sa.JSON(), nullable=True))
    op.add_column('data_table_ownership', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('tag_item', sa.Column('column_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tag_item_data_table_column', 'tag_item', 'data_table_column', ['column_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_tag_item_data_table_column', 'tag_item', type_='foreignkey')
    op.drop_column('tag_item', 'column_id')
    op.drop_column('data_table_ownership', 'type')
    op.drop_column('data_table_information', 'custom_properties')
    # ### end Alembic commands ###
