"""Add engine status checker

Revision ID: ee6d402f1d88
Revises: fa894f094d48
Create Date: 2020-02-21 00:32:36.243891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee6d402f1d88'
down_revision = 'fa894f094d48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('key_value_store', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('key_value_store', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('query_engine', sa.Column('status_checker', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_engine', 'status_checker')
    op.drop_column('key_value_store', 'updated_at')
    op.drop_column('key_value_store', 'created_at')
    # ### end Alembic commands ###
