"""add query execution metadata

Revision ID: f7b11b3e3a95
Revises: 767cf0f573bd
Create Date: 2024-06-18 19:33:42.080117

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7b11b3e3a95"
down_revision = "767cf0f573bd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_execution_metadata",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_execution_id", sa.Integer(), nullable=True),
        sa.Column("execution_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["query_execution_id"], ["query_execution.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_execution_metadata")
    # ### end Alembic commands ###
