"""add data_table_query_execution table

Revision ID: fa894f094d48
Revises: 6dc1b92d6b50
Create Date: 2020-02-06 03:34:21.779904

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fa894f094d48"
down_revision = "6dc1b92d6b50"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_table_query_execution",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("cell_id", sa.Integer(), nullable=False),
        sa.Column("query_execution_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cell_id"], ["data_cell.id"], name="data_table_query_execution_ibfk_1"
        ),
        sa.ForeignKeyConstraint(
            ["query_execution_id"],
            ["query_execution.id"],
            name="data_table_query_execution_ibfk_2",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["data_table.id"],
            name="data_table_query_execution_ibfk_3",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_table_query_execution_cell_id"),
        "data_table_query_execution",
        ["cell_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('ix_data_table_query_execution_cell_id'), table_name='data_table_query_execution')
    op.drop_table("data_table_query_execution")
    # ### end Alembic commands ###
