apiVersion: v1
kind: Service
metadata:
    name: elasticsearch
spec:
    ports:
        - name: 'elasticsearch-service'
          port: 9200
          targetPort: 9200
    selector:
        app: elasticsearch
    clusterIP: None
