OK_STATUS_CODE = 200
UNKNOWN_CLIENT_ERROR_STATUS_CODE = 400
UNAUTHORIZED_STATUS_CODE = 401
ACCESS_RESTRICTED_STATUS_CODE = 403
RESOURCE_NOT_FOUND_STATUS_CODE = 404
INVALID_SEMANTIC_STATUS_CODE = 422
LOCKED_FOR_DEPLOYMENT_STATUS_CODE = 423
UNKNOWN_SERVER_ERROR_STATUS_CODE = 500

DS_PATH = "/ds"
