#!/usr/bin/env bash -ex

# ONLY USE THIS SCRIPT WHEN
# you updated alembic from remote server
# and need to sync it back from devapp to local

USER=$(whoami)
REMOTE_REPO_FOLDER='~/code/datahub/'
MIGRATION_PATH='datahub/migrations/'

if [ $# -eq 2 ]; then
    USER=$1
    REMOTE_REPO_FOLDER=$2
elif [ $# -eq 1 ]; then
    REMOTE_REPO_FOLDER=$1
fi

rsync -rav -e ssh --exclude='*.pyc' --exclude='__pycache__' \
${USER}@dev-${USER}:${REMOTE_REPO_FOLDER}${MIGRATION_PATH} \
${MIGRATION_PATH}
