name: PythonTests
on:
    push:
        branches:
            - master
        paths:
            - '**.py'
    pull_request:
        paths:
            - '**.py'
jobs:
    pythontests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install libs
              run: >
                  sudo apt-get update && DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -y --allow-downgrades --allow-remove-essential --allow-change-held-packages
                  libsasl2-dev
                  libsasl2-modules
                  build-essential
                  python-dev
                  libssl-dev
                  libldap2-dev
            - uses: actions/setup-python@v2
              with:
                  python-version: '3.9'
            - uses: actions/cache@v2
              id: pip-cache
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('**/base.txt') }}-${{ hashFiles('**/test.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-
            - name: Install Python dependencies
              # if: steps.pip-cache.outputs.cache-hit != 'true'
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements/base.txt
                  pip install -r requirements/test.txt
            - run: PYTHONPATH=querybook/server ./querybook/scripts/run_test --python
