# This is a basic workflow to help you get started with Actions

name: Static code check

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    # Runs a single command using the runners shell
    - name: Prettify the JS code
      uses: creyD/prettier_action@v2.1
      with:
        prettier_options: '--tab-width 4 --single-quote --write datahub/webapp/**/*.{ts,tsx}'
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prettify the Python code
      uses: lgeiger/black-action@master
      with:
        args: 'datahub/{server,tests}/**/*.py --check'
    - name: Flake8 Check for Python
      uses: "tayfun/flake8-your-pr@master"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
