hints:
    - 'Format your queries by hovering over ⋮ and clicking on "Format Query".'
    - 'Change your editor theme in user settings under user icon on the bottom of the left sidebar.'
    - 'Running a long query? Click on "notify me" to be notified through email/slack on completion.'
    - 'Query not running? Check the status of the query engine on the bottom of the left sidebar.'
    - 'Use ⌘ K to search Docs/Tables.'
    - 'Need to collaborate on a DataDoc? Click the "Share" icon on top right to give access.'
    - 'Press shift + enter to launch queries quickly.'
    - 'Use ⌘S to force save DataDocs'
